import type { Metadata } from "next";
import "./globals.css";

import PromotionalBanner from "./layout/PromotionalBanner";
import Header from "./layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        {/* Top Promotional Banner */}
        <PromotionalBanner />

        {/* Header */}
   <Header
  brandLogo="/image/shoplogo.png"
  searchIcon="/image/search.svg"
  cartIcon="/image/cart.png"
  menuIcon="/images/menu.svg"
/>

        {/* Page Content */}
        <main className="container mx-auto px-4 py-6">
          {children}
        </main>

        {/* Footer (later add here) */}
      </body>
    </html>
  );
}
